{% set name = "slacker" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ae7c597025c114e202b5c880345f150f795665bfc638010cac614ede4ed5108

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip 
  run:
    - python >={{ python_min }}
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - slacker

about:
  home: https://github.com/os/slacker
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Slack API client'

extra:
  recipe-maintainers:
   - licode
   - os
   - tacaswell
   - hadim
